### ISSUE TITLE
Unsafe

### ISSUE THREAD

**Issue by ivanyuanjr** [LegitMichel777/HomeworkVerify#1]
The project is not sandboxed. People can easily execute malware in it.

**Comment by michelg10** [comment]
HomeworkVerify (aka CodeAssign) comes with no remote execution capabilities. Neither does it run with any elevated privileges by itself. any code you run on CodeAssign is completely your own and I don't see how that can be an issue.

with that said, the Mac version does come with a sandboxing feature :)
